### ISSUE TITLE
Recommended for production?

### ISSUE THREAD

**Issue by juliolitwin** [Abc-Arbitrage/zerio#5]
Hi ~

In the readme it is saying that it is not ready and is only experimental, but the project is since 2016. Can the project already be considered stable or is it better not to risk it? I saw that also an active branch (today still had commits).

Cheers.

**Comment by rverdier** [comment]
Hello,

The project is not yet stable and I would not recommend using it in production. In fact, the initial design (on `master`) is actually broken regarding the `RioRequestQueue` usage.

I'm currently experimenting a different approach in the `value-disruptor-integration` branch. I will probably merge it once sufficiently validated, and I'll update the documentation accordingly.

You can keep an eye on the project!
